name: Build
on: [push]
jobs:
  ios-build:
    name: Build iOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.6

      - name: Install
        run: bundle install && yarn install && (cd ios && pod install)

      - name: Build
        run: yarn react-native run-ios --simulator "iPhone 15"
